# Site settings
baseurl = "https://jackolney.github.io/blog/"
themesDir = "themes"
languageCode = "en-us"
title = "Jack Olney"
theme = "cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-71752366-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = "jackolney"
PygmentsCodeFences = true

[params]
  name = "Jack Olney"
  description = "blogging about science and technology"
  bio = "Science - Technology - Cars"
  # Enter optionally your twitter account
  twitter = "OlneyJack"
  enableRSS = true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # The variables below are optionally too and can be used to
  # translate or customize each string of the theme.

  # Navigation links
  home = ""
  about = "About me"
  subscribe = ""
  # Pagination links
  olderPosts = ""
  newerPosts = ""
  readMore = "More..."
  copyright = ""
  # Sharing options and author information in posts
  aboutAuthor = "Please let me know what you think"
  tweet = ""
  share = ""
  # 404 page
  title404 = ""
  subtitle404 = ""

  # Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
  iconFont = "font-awesome"
  # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
  socialIconStyle = "circle"

# Add additional social link entries underneath
[social]
    twitter  = "https://www.twitter.com/OlneyJack"
    github   = "https://www.github.com/jackolney"
