baseurl = "https://example.org/"
languageCode = "en-us"
title = "Jack Olney"
theme = "material-theme"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = "UA-71752366-1"
pygmentsuseclasses = true
PygmentsCodeFences = true
pygmentsstyle = "monokai"

[params]
    # General information
    author = "Jack Olney"
    description = "Blog about science and technology"
    copyright = "Jack Olney"
    DisqusShortname = "jackolney"

    # Repository
    provider = "github"
    repo_url = "https://github.com/JesseZhuang/hugo-material-blog"

    version = ""
    logo = "../images/avatar.png"
    favicon = ""

    permalink = "#"

    # Custom assets
    custom_css = []
    custom_js  = ["https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.5.0/highlight.min.js"]

    # Syntax highlighting theme
    # highlight_css  = ""


  [params.palette]
        primary = "red"
        accent  = "deep-red"

  [params.font]
        text = "Avenir Next"
        code = "Ubuntu Mono"


[social]
    twitter = "OlneyJack"
    github  = "jackolney"


[[menu.main]]
    name   = "Homepage"
    url    = "/"
    weight = 0

[[menu.main]]
    name   = "About Me"
    url    = "page/about-me"
    weight = 10

[[menu.main]]
    name     = "RSS feed"
    url    = "index.xml"
    weight = 20

[blackfriday]
    smartypants = true
    fractions = true
    smartDashes = true
    plainIDAnchors = true
